# Generated by Django 3.1.5 on 2021-01-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dadte',
            new_name='date',
        ),
    ]
